# Generated by Django 3.2.19 on 2024-11-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='value',
            field=models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=1),
        ),
        migrations.AddField(
            model_name='postlike',
            name='value',
            field=models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=1),
        ),
    ]
