# Generated by Django 3.2.19 on 2024-11-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
