# Generated by Django 3.2.19 on 2024-12-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
